# Generated by Django 5.1.6 on 2025-03-16 14:48

from django.db import migrations

def update_foreign_keys(apps, schema_editor):
    # Get the models
    Roteiros = apps.get_model('core', 'Roteiros')
    Avaliacoes = apps.get_model('core', 'Avaliacoes')
    Denuncias = apps.get_model('core', 'Denuncias')
    Imagens = apps.get_model('core', 'Imagens')
    User = apps.get_model('core', 'User')
    
    # Update Roteiros
    for roteiro in Roteiros.objects.all():
        try:
            user = User.objects.get(id=roteiro.user.id)
            roteiro.user = user
            roteiro.save()
        except User.DoesNotExist:
            pass
    
    # Update Avaliacoes
    for avaliacao in Avaliacoes.objects.all():
        try:
            user = User.objects.get(id=avaliacao.user.id)
            avaliacao.user = user
            avaliacao.save()
        except User.DoesNotExist:
            pass
    
    # Update Denuncias
    for denuncia in Denuncias.objects.all():
        try:
            user = User.objects.get(id=denuncia.user.id)
            denuncia.user = user
            denuncia.save()
        except User.DoesNotExist:
            pass
    
    # Update Imagens
    for imagem in Imagens.objects.all():
        if imagem.user:
            try:
                user = User.objects.get(id=imagem.user.id)
                imagem.user = user
                imagem.save()
            except User.DoesNotExist:
                pass

def reverse_update(apps, schema_editor):
    # This is a one-way migration, so we don't need to implement reverse
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_migrate_usuarios_to_user'),
    ]

    operations = [
        migrations.RunPython(update_foreign_keys, reverse_update),
    ]
