# Generated by Django 5.1.6 on 2025-03-16 23:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roteiros',
            old_name='duracao_estimada',
            new_name='duracao',
        ),
        migrations.CreateModel(
            name='RoteiroAtracao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia', models.PositiveIntegerField(default=1)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('atracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atracoes')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.roteiros')),
            ],
            options={
                'verbose_name': 'Roteiro-Atração',
                'verbose_name_plural': 'Roteiro-Atrações',
                'ordering': ['roteiro', 'ordem'],
                'unique_together': {('roteiro', 'ordem')},
            },
        ),
        migrations.AddField(
            model_name='roteiros',
            name='atracoes',
            field=models.ManyToManyField(related_name='roteiros', through='core.RoteiroAtracao', to='core.atracoes'),
        ),
    ]
